### PR TITLE
Flex theme and resize columns

### PR DESCRIPTION
**Pull request by ghinda**
> I'm creating the pull-request to keep all discussion in the same place, but let's merge it in only after everything is done.

### CODE REVIEW

**Comment by ghinda** [comment]
Nice! Some great work here! :tada:

I'm not really sure about the "container" property. Using it means more markup versions, and more theme versions (like for the `bin` theme). So it would be hard to maintain.

I think the better approach would be to only use the CSS theme for it, and not use the container property.
Can you try refactoring the `flex` theme to work with the default markup?

The `colexpand` plugin looks great so far! I'll take another look at it after you finish it up.

**Comment by armoucar** [comment]
Yep, maintenance does get complicated with more container types. I knew it from the beginning, it's just that I needed something working quickly to check what's your feedback on it. I'll get some time to work on this refactoring. Thanks!

**Comment by armoucar** [comment]
Hello @ghinda,

I tried and tried but I found it very hard to style both cases with the flexbox container with a template that doesn't duplicates any kind of code - The cases are: a bar where you can change the current pane (like it works today); and panes that are always visible and easily repositioned with flexbox.

When having a template with a `ul`, it's difficult to reposition code panes where I want.
When not having a `ul` in the template, it's difficult to create a selection pane bar.

My decision then was to have both in the template, so it's responsibility of the theme's creator to hide and show the option they want. The default `display` attribute of the new `.jotted-pane-title` is `none`. In case of creating a new flexbox theme, is enough to hide the `.jotted-nav` and show the `jotted-pane-title`.

-------

I also improved the colexpand plugin to support the console plugin and to use percentage widths on the panes.

**Comment by ghinda** [comment]
Let's approach this a bit differently then.

Since the `colexpand` plugin requires `flex-theme` to work, what do you think about merging everything into the plugin?

That would mean:
* When the plugin is constructed, manipulate the DOM to insert the new nodes you need (eg. `jotted-title`). You're already doing some of that now.
* Instead of `src/themes/flex.styl`, you would have `plugins/colexpand.styl`. Also change the class to `jotted-plugin-colexpand` in the CSS. Jotted automatically adds the class to the container, it does so for every plugin (eg. `jotted-plugin-$NAME`).

Some advantages:
* We don't need the `container` property
* We don't need to specify the theme when using the plugin
* No changes required in core
* Easier to maintain

**Comment by armoucar** [comment]
There you go... I like your suggestions, it is clean to keep everything packaged in the plugin. So there's nothing to do once you set the plugin in. Thanks

**Comment by ghinda** [comment]
Awesome work! :beers: x 10 :shipit:

I renamed the plugin to `pen` since it brings a codepen-like layout, and made a couple of tweaks to keep everything in the plugin files and not have to make any changes to core.

A quick tip about the CSS: please use vanilla CSS in the future. I'm using Stylus just for `nib` and bundling files. So no nesting, semicolonless-ing, variables, etc..

Thanks!

**Comment by ghinda** [comment]
And released as `1.5.0`.

**Pull request merged**
